/*
 * generated by Xtext 2.27.0
 */
package nl.tue.gtl.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import nl.tue.gtl.ide.contentassist.antlr.internal.InternalTQLParser;
import nl.tue.gtl.services.TQLGrammarAccess;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class TQLParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(TQLGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, TQLGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getExpressionAccess().getAlternatives(), "rule__Expression__Alternatives");
			builder.put(grammarAccess.getConstantExpressionAccess().getAlternatives(), "rule__ConstantExpression__Alternatives");
			builder.put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
			builder.put(grammarAccess.getEBooleanAccess().getAlternatives(), "rule__EBoolean__Alternatives");
			builder.put(grammarAccess.getEFloatAccess().getAlternatives_4_0(), "rule__EFloat__Alternatives_4_0");
			builder.put(grammarAccess.getBinaryFunctionAccess().getAlternatives(), "rule__BinaryFunction__Alternatives");
			builder.put(grammarAccess.getTypeAccess().getAlternatives(), "rule__Type__Alternatives");
			builder.put(grammarAccess.getBinaryOperationExpressionAccess().getGroup(), "rule__BinaryOperationExpression__Group__0");
			builder.put(grammarAccess.getBinaryOperationExpressionAccess().getGroup_2(), "rule__BinaryOperationExpression__Group_2__0");
			builder.put(grammarAccess.getParameterExpressionAccess().getGroup(), "rule__ParameterExpression__Group__0");
			builder.put(grammarAccess.getStringConstantExpressionAccess().getGroup(), "rule__StringConstantExpression__Group__0");
			builder.put(grammarAccess.getBooleanConstantExpressionAccess().getGroup(), "rule__BooleanConstantExpression__Group__0");
			builder.put(grammarAccess.getIntegerConstantExpressionAccess().getGroup(), "rule__IntegerConstantExpression__Group__0");
			builder.put(grammarAccess.getInExpressionAccess().getGroup(), "rule__InExpression__Group__0");
			builder.put(grammarAccess.getInExpressionAccess().getGroup_2(), "rule__InExpression__Group_2__0");
			builder.put(grammarAccess.getInExpressionAccess().getGroup_6(), "rule__InExpression__Group_6__0");
			builder.put(grammarAccess.getParseExpressionAccess().getGroup(), "rule__ParseExpression__Group__0");
			builder.put(grammarAccess.getParseExpressionAccess().getGroup_2(), "rule__ParseExpression__Group_2__0");
			builder.put(grammarAccess.getFloatConstantExpressionAccess().getGroup(), "rule__FloatConstantExpression__Group__0");
			builder.put(grammarAccess.getEIntAccess().getGroup(), "rule__EInt__Group__0");
			builder.put(grammarAccess.getEFloatAccess().getGroup(), "rule__EFloat__Group__0");
			builder.put(grammarAccess.getEFloatAccess().getGroup_4(), "rule__EFloat__Group_4__0");
			builder.put(grammarAccess.getBinaryOperationExpressionAccess().getOperationAssignment_2_1(), "rule__BinaryOperationExpression__OperationAssignment_2_1");
			builder.put(grammarAccess.getBinaryOperationExpressionAccess().getLeftAssignment_4(), "rule__BinaryOperationExpression__LeftAssignment_4");
			builder.put(grammarAccess.getBinaryOperationExpressionAccess().getRightAssignment_6(), "rule__BinaryOperationExpression__RightAssignment_6");
			builder.put(grammarAccess.getStringConstantExpressionAccess().getValueAssignment_3(), "rule__StringConstantExpression__ValueAssignment_3");
			builder.put(grammarAccess.getBooleanConstantExpressionAccess().getValueAssignment_0(), "rule__BooleanConstantExpression__ValueAssignment_0");
			builder.put(grammarAccess.getIntegerConstantExpressionAccess().getValueAssignment_3(), "rule__IntegerConstantExpression__ValueAssignment_3");
			builder.put(grammarAccess.getInExpressionAccess().getStatementAssignment_2_1(), "rule__InExpression__StatementAssignment_2_1");
			builder.put(grammarAccess.getInExpressionAccess().getConstantSetAssignment_5(), "rule__InExpression__ConstantSetAssignment_5");
			builder.put(grammarAccess.getInExpressionAccess().getConstantSetAssignment_6_1(), "rule__InExpression__ConstantSetAssignment_6_1");
			builder.put(grammarAccess.getParseExpressionAccess().getOutputTypeAssignment_2_1(), "rule__ParseExpression__OutputTypeAssignment_2_1");
			builder.put(grammarAccess.getParseExpressionAccess().getExpressionAssignment_4(), "rule__ParseExpression__ExpressionAssignment_4");
			builder.put(grammarAccess.getFloatConstantExpressionAccess().getValueAssignment_3(), "rule__FloatConstantExpression__ValueAssignment_3");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private TQLGrammarAccess grammarAccess;

	@Override
	protected InternalTQLParser createParser() {
		InternalTQLParser result = new InternalTQLParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public TQLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(TQLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
