/*
 * generated by Xtext 2.27.0
 */
package nl.tue.gtl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class TQLAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("nl/tue/gtl/parser/antlr/internal/InternalTQL.tokens");
	}
}
