/*
 * generated by Xtext 2.27.0
 */
package nl.tue.gtl.parser.antlr;

import com.google.inject.Inject;
import nl.tue.gtl.parser.antlr.internal.InternalTQLParser;
import nl.tue.gtl.services.TQLGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class TQLParser extends AbstractAntlrParser {

	@Inject
	private TQLGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalTQLParser createParser(XtextTokenStream stream) {
		return new InternalTQLParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "TQL";
	}

	public TQLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(TQLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
