/*
 * generated by Xtext 2.27.0
 */
package org.xtext.example.tql.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class TQLUiModule extends AbstractTQLUiModule {

	public TQLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
