/*
 * generated by Xtext 2.27.0
 */
package nl.tue.gtl.ui.tests;

import com.google.inject.Injector;
import nl.tue.gtl.tql.ui.internal.TqlActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class TQLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return TqlActivator.getInstance().getInjector("nl.tue.gtl.TQL");
	}

}
