/**
 * generated by Xtext 2.27.0
 */
package nl.tue.gtl.domainmodel;

import nl.tue.gtl.tql.model.ModelPackage;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see nl.tue.gtl.domainmodel.DomainmodelFactory
 * @model kind="package"
 * @generated
 */
public interface DomainmodelPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "domainmodel";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.example.org/domainmodel/TQL";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "domainmodel";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  DomainmodelPackage eINSTANCE = nl.tue.gtl.domainmodel.impl.DomainmodelPackageImpl.init();

  /**
   * The meta object id for the '{@link nl.tue.gtl.domainmodel.impl.TQLImpl <em>TQL</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see nl.tue.gtl.domainmodel.impl.TQLImpl
   * @see nl.tue.gtl.domainmodel.impl.DomainmodelPackageImpl#getTQL()
   * @generated
   */
  int TQL = 0;

  /**
   * The feature id for the '<em><b>Blocks</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TQL__BLOCKS = 0;

  /**
   * The number of structural features of the '<em>TQL</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TQL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link nl.tue.gtl.domainmodel.impl.And_ExpressionImpl <em>And Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see nl.tue.gtl.domainmodel.impl.And_ExpressionImpl
   * @see nl.tue.gtl.domainmodel.impl.DomainmodelPackageImpl#getAnd_Expression()
   * @generated
   */
  int AND_EXPRESSION = 1;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND_EXPRESSION__LEFT = ModelPackage.EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Operator</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND_EXPRESSION__OPERATOR = ModelPackage.EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND_EXPRESSION__RIGHT = ModelPackage.EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>And Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND_EXPRESSION_FEATURE_COUNT = ModelPackage.EXPRESSION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link nl.tue.gtl.domainmodel.impl.Or_ExpressionImpl <em>Or Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see nl.tue.gtl.domainmodel.impl.Or_ExpressionImpl
   * @see nl.tue.gtl.domainmodel.impl.DomainmodelPackageImpl#getOr_Expression()
   * @generated
   */
  int OR_EXPRESSION = 2;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OR_EXPRESSION__LEFT = ModelPackage.EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Operator</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OR_EXPRESSION__OPERATOR = ModelPackage.EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OR_EXPRESSION__RIGHT = ModelPackage.EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Or Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OR_EXPRESSION_FEATURE_COUNT = ModelPackage.EXPRESSION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link nl.tue.gtl.domainmodel.impl.Equals_ExpressionImpl <em>Equals Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see nl.tue.gtl.domainmodel.impl.Equals_ExpressionImpl
   * @see nl.tue.gtl.domainmodel.impl.DomainmodelPackageImpl#getEquals_Expression()
   * @generated
   */
  int EQUALS_EXPRESSION = 3;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EQUALS_EXPRESSION__LEFT = ModelPackage.EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Operator</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EQUALS_EXPRESSION__OPERATOR = ModelPackage.EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EQUALS_EXPRESSION__RIGHT = ModelPackage.EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Equals Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EQUALS_EXPRESSION_FEATURE_COUNT = ModelPackage.EXPRESSION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link nl.tue.gtl.domainmodel.impl.NotEquals_ExpressionImpl <em>Not Equals Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see nl.tue.gtl.domainmodel.impl.NotEquals_ExpressionImpl
   * @see nl.tue.gtl.domainmodel.impl.DomainmodelPackageImpl#getNotEquals_Expression()
   * @generated
   */
  int NOT_EQUALS_EXPRESSION = 4;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NOT_EQUALS_EXPRESSION__LEFT = ModelPackage.EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Operator</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NOT_EQUALS_EXPRESSION__OPERATOR = ModelPackage.EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NOT_EQUALS_EXPRESSION__RIGHT = ModelPackage.EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Not Equals Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NOT_EQUALS_EXPRESSION_FEATURE_COUNT = ModelPackage.EXPRESSION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link nl.tue.gtl.domainmodel.impl.Less_ExpressionImpl <em>Less Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see nl.tue.gtl.domainmodel.impl.Less_ExpressionImpl
   * @see nl.tue.gtl.domainmodel.impl.DomainmodelPackageImpl#getLess_Expression()
   * @generated
   */
  int LESS_EXPRESSION = 5;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LESS_EXPRESSION__LEFT = ModelPackage.EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Operator</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LESS_EXPRESSION__OPERATOR = ModelPackage.EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LESS_EXPRESSION__RIGHT = ModelPackage.EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Less Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LESS_EXPRESSION_FEATURE_COUNT = ModelPackage.EXPRESSION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link nl.tue.gtl.domainmodel.impl.Greater_ExpressionImpl <em>Greater Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see nl.tue.gtl.domainmodel.impl.Greater_ExpressionImpl
   * @see nl.tue.gtl.domainmodel.impl.DomainmodelPackageImpl#getGreater_Expression()
   * @generated
   */
  int GREATER_EXPRESSION = 6;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GREATER_EXPRESSION__LEFT = ModelPackage.EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Operator</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GREATER_EXPRESSION__OPERATOR = ModelPackage.EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GREATER_EXPRESSION__RIGHT = ModelPackage.EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Greater Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GREATER_EXPRESSION_FEATURE_COUNT = ModelPackage.EXPRESSION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link nl.tue.gtl.domainmodel.impl.Multiply_ExpressionImpl <em>Multiply Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see nl.tue.gtl.domainmodel.impl.Multiply_ExpressionImpl
   * @see nl.tue.gtl.domainmodel.impl.DomainmodelPackageImpl#getMultiply_Expression()
   * @generated
   */
  int MULTIPLY_EXPRESSION = 7;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTIPLY_EXPRESSION__LEFT = ModelPackage.EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Operator</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTIPLY_EXPRESSION__OPERATOR = ModelPackage.EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTIPLY_EXPRESSION__RIGHT = ModelPackage.EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Multiply Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTIPLY_EXPRESSION_FEATURE_COUNT = ModelPackage.EXPRESSION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link nl.tue.gtl.domainmodel.impl.Divide_ExpressionImpl <em>Divide Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see nl.tue.gtl.domainmodel.impl.Divide_ExpressionImpl
   * @see nl.tue.gtl.domainmodel.impl.DomainmodelPackageImpl#getDivide_Expression()
   * @generated
   */
  int DIVIDE_EXPRESSION = 8;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIVIDE_EXPRESSION__LEFT = ModelPackage.EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Operator</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIVIDE_EXPRESSION__OPERATOR = ModelPackage.EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIVIDE_EXPRESSION__RIGHT = ModelPackage.EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Divide Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIVIDE_EXPRESSION_FEATURE_COUNT = ModelPackage.EXPRESSION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link nl.tue.gtl.domainmodel.impl.Add_ExpressionImpl <em>Add Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see nl.tue.gtl.domainmodel.impl.Add_ExpressionImpl
   * @see nl.tue.gtl.domainmodel.impl.DomainmodelPackageImpl#getAdd_Expression()
   * @generated
   */
  int ADD_EXPRESSION = 9;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADD_EXPRESSION__LEFT = ModelPackage.EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Operator</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADD_EXPRESSION__OPERATOR = ModelPackage.EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADD_EXPRESSION__RIGHT = ModelPackage.EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Add Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADD_EXPRESSION_FEATURE_COUNT = ModelPackage.EXPRESSION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link nl.tue.gtl.domainmodel.impl.Subtract_ExpressionImpl <em>Subtract Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see nl.tue.gtl.domainmodel.impl.Subtract_ExpressionImpl
   * @see nl.tue.gtl.domainmodel.impl.DomainmodelPackageImpl#getSubtract_Expression()
   * @generated
   */
  int SUBTRACT_EXPRESSION = 10;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUBTRACT_EXPRESSION__LEFT = ModelPackage.EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Operator</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUBTRACT_EXPRESSION__OPERATOR = ModelPackage.EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUBTRACT_EXPRESSION__RIGHT = ModelPackage.EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Subtract Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUBTRACT_EXPRESSION_FEATURE_COUNT = ModelPackage.EXPRESSION_FEATURE_COUNT + 3;


  /**
   * Returns the meta object for class '{@link nl.tue.gtl.domainmodel.TQL <em>TQL</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>TQL</em>'.
   * @see nl.tue.gtl.domainmodel.TQL
   * @generated
   */
  EClass getTQL();

  /**
   * Returns the meta object for the containment reference list '{@link nl.tue.gtl.domainmodel.TQL#getBlocks <em>Blocks</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Blocks</em>'.
   * @see nl.tue.gtl.domainmodel.TQL#getBlocks()
   * @see #getTQL()
   * @generated
   */
  EReference getTQL_Blocks();

  /**
   * Returns the meta object for class '{@link nl.tue.gtl.domainmodel.And_Expression <em>And Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>And Expression</em>'.
   * @see nl.tue.gtl.domainmodel.And_Expression
   * @generated
   */
  EClass getAnd_Expression();

  /**
   * Returns the meta object for the containment reference '{@link nl.tue.gtl.domainmodel.And_Expression#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see nl.tue.gtl.domainmodel.And_Expression#getLeft()
   * @see #getAnd_Expression()
   * @generated
   */
  EReference getAnd_Expression_Left();

  /**
   * Returns the meta object for the attribute '{@link nl.tue.gtl.domainmodel.And_Expression#getOperator <em>Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Operator</em>'.
   * @see nl.tue.gtl.domainmodel.And_Expression#getOperator()
   * @see #getAnd_Expression()
   * @generated
   */
  EAttribute getAnd_Expression_Operator();

  /**
   * Returns the meta object for the containment reference '{@link nl.tue.gtl.domainmodel.And_Expression#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see nl.tue.gtl.domainmodel.And_Expression#getRight()
   * @see #getAnd_Expression()
   * @generated
   */
  EReference getAnd_Expression_Right();

  /**
   * Returns the meta object for class '{@link nl.tue.gtl.domainmodel.Or_Expression <em>Or Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Or Expression</em>'.
   * @see nl.tue.gtl.domainmodel.Or_Expression
   * @generated
   */
  EClass getOr_Expression();

  /**
   * Returns the meta object for the containment reference '{@link nl.tue.gtl.domainmodel.Or_Expression#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see nl.tue.gtl.domainmodel.Or_Expression#getLeft()
   * @see #getOr_Expression()
   * @generated
   */
  EReference getOr_Expression_Left();

  /**
   * Returns the meta object for the attribute '{@link nl.tue.gtl.domainmodel.Or_Expression#getOperator <em>Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Operator</em>'.
   * @see nl.tue.gtl.domainmodel.Or_Expression#getOperator()
   * @see #getOr_Expression()
   * @generated
   */
  EAttribute getOr_Expression_Operator();

  /**
   * Returns the meta object for the containment reference '{@link nl.tue.gtl.domainmodel.Or_Expression#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see nl.tue.gtl.domainmodel.Or_Expression#getRight()
   * @see #getOr_Expression()
   * @generated
   */
  EReference getOr_Expression_Right();

  /**
   * Returns the meta object for class '{@link nl.tue.gtl.domainmodel.Equals_Expression <em>Equals Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Equals Expression</em>'.
   * @see nl.tue.gtl.domainmodel.Equals_Expression
   * @generated
   */
  EClass getEquals_Expression();

  /**
   * Returns the meta object for the containment reference '{@link nl.tue.gtl.domainmodel.Equals_Expression#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see nl.tue.gtl.domainmodel.Equals_Expression#getLeft()
   * @see #getEquals_Expression()
   * @generated
   */
  EReference getEquals_Expression_Left();

  /**
   * Returns the meta object for the attribute '{@link nl.tue.gtl.domainmodel.Equals_Expression#getOperator <em>Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Operator</em>'.
   * @see nl.tue.gtl.domainmodel.Equals_Expression#getOperator()
   * @see #getEquals_Expression()
   * @generated
   */
  EAttribute getEquals_Expression_Operator();

  /**
   * Returns the meta object for the containment reference '{@link nl.tue.gtl.domainmodel.Equals_Expression#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see nl.tue.gtl.domainmodel.Equals_Expression#getRight()
   * @see #getEquals_Expression()
   * @generated
   */
  EReference getEquals_Expression_Right();

  /**
   * Returns the meta object for class '{@link nl.tue.gtl.domainmodel.NotEquals_Expression <em>Not Equals Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Not Equals Expression</em>'.
   * @see nl.tue.gtl.domainmodel.NotEquals_Expression
   * @generated
   */
  EClass getNotEquals_Expression();

  /**
   * Returns the meta object for the containment reference '{@link nl.tue.gtl.domainmodel.NotEquals_Expression#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see nl.tue.gtl.domainmodel.NotEquals_Expression#getLeft()
   * @see #getNotEquals_Expression()
   * @generated
   */
  EReference getNotEquals_Expression_Left();

  /**
   * Returns the meta object for the attribute '{@link nl.tue.gtl.domainmodel.NotEquals_Expression#getOperator <em>Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Operator</em>'.
   * @see nl.tue.gtl.domainmodel.NotEquals_Expression#getOperator()
   * @see #getNotEquals_Expression()
   * @generated
   */
  EAttribute getNotEquals_Expression_Operator();

  /**
   * Returns the meta object for the containment reference '{@link nl.tue.gtl.domainmodel.NotEquals_Expression#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see nl.tue.gtl.domainmodel.NotEquals_Expression#getRight()
   * @see #getNotEquals_Expression()
   * @generated
   */
  EReference getNotEquals_Expression_Right();

  /**
   * Returns the meta object for class '{@link nl.tue.gtl.domainmodel.Less_Expression <em>Less Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Less Expression</em>'.
   * @see nl.tue.gtl.domainmodel.Less_Expression
   * @generated
   */
  EClass getLess_Expression();

  /**
   * Returns the meta object for the containment reference '{@link nl.tue.gtl.domainmodel.Less_Expression#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see nl.tue.gtl.domainmodel.Less_Expression#getLeft()
   * @see #getLess_Expression()
   * @generated
   */
  EReference getLess_Expression_Left();

  /**
   * Returns the meta object for the attribute '{@link nl.tue.gtl.domainmodel.Less_Expression#getOperator <em>Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Operator</em>'.
   * @see nl.tue.gtl.domainmodel.Less_Expression#getOperator()
   * @see #getLess_Expression()
   * @generated
   */
  EAttribute getLess_Expression_Operator();

  /**
   * Returns the meta object for the containment reference '{@link nl.tue.gtl.domainmodel.Less_Expression#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see nl.tue.gtl.domainmodel.Less_Expression#getRight()
   * @see #getLess_Expression()
   * @generated
   */
  EReference getLess_Expression_Right();

  /**
   * Returns the meta object for class '{@link nl.tue.gtl.domainmodel.Greater_Expression <em>Greater Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Greater Expression</em>'.
   * @see nl.tue.gtl.domainmodel.Greater_Expression
   * @generated
   */
  EClass getGreater_Expression();

  /**
   * Returns the meta object for the containment reference '{@link nl.tue.gtl.domainmodel.Greater_Expression#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see nl.tue.gtl.domainmodel.Greater_Expression#getLeft()
   * @see #getGreater_Expression()
   * @generated
   */
  EReference getGreater_Expression_Left();

  /**
   * Returns the meta object for the attribute '{@link nl.tue.gtl.domainmodel.Greater_Expression#getOperator <em>Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Operator</em>'.
   * @see nl.tue.gtl.domainmodel.Greater_Expression#getOperator()
   * @see #getGreater_Expression()
   * @generated
   */
  EAttribute getGreater_Expression_Operator();

  /**
   * Returns the meta object for the containment reference '{@link nl.tue.gtl.domainmodel.Greater_Expression#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see nl.tue.gtl.domainmodel.Greater_Expression#getRight()
   * @see #getGreater_Expression()
   * @generated
   */
  EReference getGreater_Expression_Right();

  /**
   * Returns the meta object for class '{@link nl.tue.gtl.domainmodel.Multiply_Expression <em>Multiply Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Multiply Expression</em>'.
   * @see nl.tue.gtl.domainmodel.Multiply_Expression
   * @generated
   */
  EClass getMultiply_Expression();

  /**
   * Returns the meta object for the containment reference '{@link nl.tue.gtl.domainmodel.Multiply_Expression#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see nl.tue.gtl.domainmodel.Multiply_Expression#getLeft()
   * @see #getMultiply_Expression()
   * @generated
   */
  EReference getMultiply_Expression_Left();

  /**
   * Returns the meta object for the attribute '{@link nl.tue.gtl.domainmodel.Multiply_Expression#getOperator <em>Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Operator</em>'.
   * @see nl.tue.gtl.domainmodel.Multiply_Expression#getOperator()
   * @see #getMultiply_Expression()
   * @generated
   */
  EAttribute getMultiply_Expression_Operator();

  /**
   * Returns the meta object for the containment reference '{@link nl.tue.gtl.domainmodel.Multiply_Expression#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see nl.tue.gtl.domainmodel.Multiply_Expression#getRight()
   * @see #getMultiply_Expression()
   * @generated
   */
  EReference getMultiply_Expression_Right();

  /**
   * Returns the meta object for class '{@link nl.tue.gtl.domainmodel.Divide_Expression <em>Divide Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Divide Expression</em>'.
   * @see nl.tue.gtl.domainmodel.Divide_Expression
   * @generated
   */
  EClass getDivide_Expression();

  /**
   * Returns the meta object for the containment reference '{@link nl.tue.gtl.domainmodel.Divide_Expression#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see nl.tue.gtl.domainmodel.Divide_Expression#getLeft()
   * @see #getDivide_Expression()
   * @generated
   */
  EReference getDivide_Expression_Left();

  /**
   * Returns the meta object for the attribute '{@link nl.tue.gtl.domainmodel.Divide_Expression#getOperator <em>Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Operator</em>'.
   * @see nl.tue.gtl.domainmodel.Divide_Expression#getOperator()
   * @see #getDivide_Expression()
   * @generated
   */
  EAttribute getDivide_Expression_Operator();

  /**
   * Returns the meta object for the containment reference '{@link nl.tue.gtl.domainmodel.Divide_Expression#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see nl.tue.gtl.domainmodel.Divide_Expression#getRight()
   * @see #getDivide_Expression()
   * @generated
   */
  EReference getDivide_Expression_Right();

  /**
   * Returns the meta object for class '{@link nl.tue.gtl.domainmodel.Add_Expression <em>Add Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Add Expression</em>'.
   * @see nl.tue.gtl.domainmodel.Add_Expression
   * @generated
   */
  EClass getAdd_Expression();

  /**
   * Returns the meta object for the containment reference '{@link nl.tue.gtl.domainmodel.Add_Expression#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see nl.tue.gtl.domainmodel.Add_Expression#getLeft()
   * @see #getAdd_Expression()
   * @generated
   */
  EReference getAdd_Expression_Left();

  /**
   * Returns the meta object for the attribute '{@link nl.tue.gtl.domainmodel.Add_Expression#getOperator <em>Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Operator</em>'.
   * @see nl.tue.gtl.domainmodel.Add_Expression#getOperator()
   * @see #getAdd_Expression()
   * @generated
   */
  EAttribute getAdd_Expression_Operator();

  /**
   * Returns the meta object for the containment reference '{@link nl.tue.gtl.domainmodel.Add_Expression#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see nl.tue.gtl.domainmodel.Add_Expression#getRight()
   * @see #getAdd_Expression()
   * @generated
   */
  EReference getAdd_Expression_Right();

  /**
   * Returns the meta object for class '{@link nl.tue.gtl.domainmodel.Subtract_Expression <em>Subtract Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Subtract Expression</em>'.
   * @see nl.tue.gtl.domainmodel.Subtract_Expression
   * @generated
   */
  EClass getSubtract_Expression();

  /**
   * Returns the meta object for the containment reference '{@link nl.tue.gtl.domainmodel.Subtract_Expression#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see nl.tue.gtl.domainmodel.Subtract_Expression#getLeft()
   * @see #getSubtract_Expression()
   * @generated
   */
  EReference getSubtract_Expression_Left();

  /**
   * Returns the meta object for the attribute '{@link nl.tue.gtl.domainmodel.Subtract_Expression#getOperator <em>Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Operator</em>'.
   * @see nl.tue.gtl.domainmodel.Subtract_Expression#getOperator()
   * @see #getSubtract_Expression()
   * @generated
   */
  EAttribute getSubtract_Expression_Operator();

  /**
   * Returns the meta object for the containment reference '{@link nl.tue.gtl.domainmodel.Subtract_Expression#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see nl.tue.gtl.domainmodel.Subtract_Expression#getRight()
   * @see #getSubtract_Expression()
   * @generated
   */
  EReference getSubtract_Expression_Right();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  DomainmodelFactory getDomainmodelFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link nl.tue.gtl.domainmodel.impl.TQLImpl <em>TQL</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see nl.tue.gtl.domainmodel.impl.TQLImpl
     * @see nl.tue.gtl.domainmodel.impl.DomainmodelPackageImpl#getTQL()
     * @generated
     */
    EClass TQL = eINSTANCE.getTQL();

    /**
     * The meta object literal for the '<em><b>Blocks</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TQL__BLOCKS = eINSTANCE.getTQL_Blocks();

    /**
     * The meta object literal for the '{@link nl.tue.gtl.domainmodel.impl.And_ExpressionImpl <em>And Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see nl.tue.gtl.domainmodel.impl.And_ExpressionImpl
     * @see nl.tue.gtl.domainmodel.impl.DomainmodelPackageImpl#getAnd_Expression()
     * @generated
     */
    EClass AND_EXPRESSION = eINSTANCE.getAnd_Expression();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AND_EXPRESSION__LEFT = eINSTANCE.getAnd_Expression_Left();

    /**
     * The meta object literal for the '<em><b>Operator</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute AND_EXPRESSION__OPERATOR = eINSTANCE.getAnd_Expression_Operator();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AND_EXPRESSION__RIGHT = eINSTANCE.getAnd_Expression_Right();

    /**
     * The meta object literal for the '{@link nl.tue.gtl.domainmodel.impl.Or_ExpressionImpl <em>Or Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see nl.tue.gtl.domainmodel.impl.Or_ExpressionImpl
     * @see nl.tue.gtl.domainmodel.impl.DomainmodelPackageImpl#getOr_Expression()
     * @generated
     */
    EClass OR_EXPRESSION = eINSTANCE.getOr_Expression();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OR_EXPRESSION__LEFT = eINSTANCE.getOr_Expression_Left();

    /**
     * The meta object literal for the '<em><b>Operator</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OR_EXPRESSION__OPERATOR = eINSTANCE.getOr_Expression_Operator();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OR_EXPRESSION__RIGHT = eINSTANCE.getOr_Expression_Right();

    /**
     * The meta object literal for the '{@link nl.tue.gtl.domainmodel.impl.Equals_ExpressionImpl <em>Equals Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see nl.tue.gtl.domainmodel.impl.Equals_ExpressionImpl
     * @see nl.tue.gtl.domainmodel.impl.DomainmodelPackageImpl#getEquals_Expression()
     * @generated
     */
    EClass EQUALS_EXPRESSION = eINSTANCE.getEquals_Expression();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EQUALS_EXPRESSION__LEFT = eINSTANCE.getEquals_Expression_Left();

    /**
     * The meta object literal for the '<em><b>Operator</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EQUALS_EXPRESSION__OPERATOR = eINSTANCE.getEquals_Expression_Operator();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EQUALS_EXPRESSION__RIGHT = eINSTANCE.getEquals_Expression_Right();

    /**
     * The meta object literal for the '{@link nl.tue.gtl.domainmodel.impl.NotEquals_ExpressionImpl <em>Not Equals Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see nl.tue.gtl.domainmodel.impl.NotEquals_ExpressionImpl
     * @see nl.tue.gtl.domainmodel.impl.DomainmodelPackageImpl#getNotEquals_Expression()
     * @generated
     */
    EClass NOT_EQUALS_EXPRESSION = eINSTANCE.getNotEquals_Expression();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NOT_EQUALS_EXPRESSION__LEFT = eINSTANCE.getNotEquals_Expression_Left();

    /**
     * The meta object literal for the '<em><b>Operator</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NOT_EQUALS_EXPRESSION__OPERATOR = eINSTANCE.getNotEquals_Expression_Operator();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NOT_EQUALS_EXPRESSION__RIGHT = eINSTANCE.getNotEquals_Expression_Right();

    /**
     * The meta object literal for the '{@link nl.tue.gtl.domainmodel.impl.Less_ExpressionImpl <em>Less Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see nl.tue.gtl.domainmodel.impl.Less_ExpressionImpl
     * @see nl.tue.gtl.domainmodel.impl.DomainmodelPackageImpl#getLess_Expression()
     * @generated
     */
    EClass LESS_EXPRESSION = eINSTANCE.getLess_Expression();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LESS_EXPRESSION__LEFT = eINSTANCE.getLess_Expression_Left();

    /**
     * The meta object literal for the '<em><b>Operator</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LESS_EXPRESSION__OPERATOR = eINSTANCE.getLess_Expression_Operator();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LESS_EXPRESSION__RIGHT = eINSTANCE.getLess_Expression_Right();

    /**
     * The meta object literal for the '{@link nl.tue.gtl.domainmodel.impl.Greater_ExpressionImpl <em>Greater Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see nl.tue.gtl.domainmodel.impl.Greater_ExpressionImpl
     * @see nl.tue.gtl.domainmodel.impl.DomainmodelPackageImpl#getGreater_Expression()
     * @generated
     */
    EClass GREATER_EXPRESSION = eINSTANCE.getGreater_Expression();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GREATER_EXPRESSION__LEFT = eINSTANCE.getGreater_Expression_Left();

    /**
     * The meta object literal for the '<em><b>Operator</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GREATER_EXPRESSION__OPERATOR = eINSTANCE.getGreater_Expression_Operator();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GREATER_EXPRESSION__RIGHT = eINSTANCE.getGreater_Expression_Right();

    /**
     * The meta object literal for the '{@link nl.tue.gtl.domainmodel.impl.Multiply_ExpressionImpl <em>Multiply Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see nl.tue.gtl.domainmodel.impl.Multiply_ExpressionImpl
     * @see nl.tue.gtl.domainmodel.impl.DomainmodelPackageImpl#getMultiply_Expression()
     * @generated
     */
    EClass MULTIPLY_EXPRESSION = eINSTANCE.getMultiply_Expression();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MULTIPLY_EXPRESSION__LEFT = eINSTANCE.getMultiply_Expression_Left();

    /**
     * The meta object literal for the '<em><b>Operator</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MULTIPLY_EXPRESSION__OPERATOR = eINSTANCE.getMultiply_Expression_Operator();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MULTIPLY_EXPRESSION__RIGHT = eINSTANCE.getMultiply_Expression_Right();

    /**
     * The meta object literal for the '{@link nl.tue.gtl.domainmodel.impl.Divide_ExpressionImpl <em>Divide Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see nl.tue.gtl.domainmodel.impl.Divide_ExpressionImpl
     * @see nl.tue.gtl.domainmodel.impl.DomainmodelPackageImpl#getDivide_Expression()
     * @generated
     */
    EClass DIVIDE_EXPRESSION = eINSTANCE.getDivide_Expression();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DIVIDE_EXPRESSION__LEFT = eINSTANCE.getDivide_Expression_Left();

    /**
     * The meta object literal for the '<em><b>Operator</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DIVIDE_EXPRESSION__OPERATOR = eINSTANCE.getDivide_Expression_Operator();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DIVIDE_EXPRESSION__RIGHT = eINSTANCE.getDivide_Expression_Right();

    /**
     * The meta object literal for the '{@link nl.tue.gtl.domainmodel.impl.Add_ExpressionImpl <em>Add Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see nl.tue.gtl.domainmodel.impl.Add_ExpressionImpl
     * @see nl.tue.gtl.domainmodel.impl.DomainmodelPackageImpl#getAdd_Expression()
     * @generated
     */
    EClass ADD_EXPRESSION = eINSTANCE.getAdd_Expression();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ADD_EXPRESSION__LEFT = eINSTANCE.getAdd_Expression_Left();

    /**
     * The meta object literal for the '<em><b>Operator</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ADD_EXPRESSION__OPERATOR = eINSTANCE.getAdd_Expression_Operator();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ADD_EXPRESSION__RIGHT = eINSTANCE.getAdd_Expression_Right();

    /**
     * The meta object literal for the '{@link nl.tue.gtl.domainmodel.impl.Subtract_ExpressionImpl <em>Subtract Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see nl.tue.gtl.domainmodel.impl.Subtract_ExpressionImpl
     * @see nl.tue.gtl.domainmodel.impl.DomainmodelPackageImpl#getSubtract_Expression()
     * @generated
     */
    EClass SUBTRACT_EXPRESSION = eINSTANCE.getSubtract_Expression();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SUBTRACT_EXPRESSION__LEFT = eINSTANCE.getSubtract_Expression_Left();

    /**
     * The meta object literal for the '<em><b>Operator</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SUBTRACT_EXPRESSION__OPERATOR = eINSTANCE.getSubtract_Expression_Operator();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SUBTRACT_EXPRESSION__RIGHT = eINSTANCE.getSubtract_Expression_Right();

  }

} //DomainmodelPackage
