<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="tqlModel" nsURI="http://www.example.org/tqlModel" nsPrefix="tqlModel">
  <eClassifiers xsi:type="ecore:EEnum" name="Type">
    <eLiterals name="string"/>
    <eLiterals name="integer" value="1"/>
    <eLiterals name="floats" value="2"/>
    <eLiterals name="sets" value="3"/>
    <eLiterals name="DateTime" value="4"/>
    <eLiterals name="Null" value="5"/>
    <eLiterals name="bool" value="6"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="parameterExpression" eSuperTypes="#//Expression"/>
  <eClassifiers xsi:type="ecore:EClass" name="StringConstantExpression" eSuperTypes="#//ConstantExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExpressionParameter" eSuperTypes="#//Parameter">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Expression" lowerBound="1"
        eType="#//Expression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReferenceParameter" eSuperTypes="#//Parameter">
    <eStructuralFeatures xsi:type="ecore:EReference" name="references" lowerBound="1"
        eType="#//TableField"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanConstantExpression" eSuperTypes="#//ConstantExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="IntegerConstantExpression" eSuperTypes="#//ConstantExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MappingSourceTable" eSuperTypes="#//Table"/>
  <eClassifiers xsi:type="ecore:EClass" name="Mapping" eSuperTypes="#//Block">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" upperBound="-1"
        eType="#//MappingSourceTable" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" upperBound="-1"
        eType="#//MappingTargetTable" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fields" lowerBound="1"
        upperBound="-1" eType="#//MappingField"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InExpression" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="statement" eType="#//Expression"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constantSet" lowerBound="1"
        upperBound="-1" eType="#//ConstantExpression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Table" eSuperTypes="#//Block">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="columns" lowerBound="1"
        upperBound="-1" eType="#//TableField" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConditionalStatement" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" lowerBound="1"
        eType="#//Expression"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="booleanExression" eType="#//BooleanOperationExpression"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ifBody" lowerBound="1"
        upperBound="-1" eType="#//Statement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elseBody" lowerBound="1"
        upperBound="-1" eType="#//Statement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParseExpression" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="outputType" eType="#//Type"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1"
        eType="#//Expression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FloatConstantExpression" eSuperTypes="#//ConstantExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parameter" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ConstantExpression" abstract="true"
      interface="true" eSuperTypes="#//Expression"/>
  <eClassifiers xsi:type="ecore:EClass" name="MappingTargetTable" eSuperTypes="#//Table"/>
  <eClassifiers xsi:type="ecore:EClass" name="MappingField">
    <eStructuralFeatures xsi:type="ecore:EReference" name="souceField" lowerBound="1"
        eType="#//TableField"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetField" lowerBound="1"
        eType="#//TableField"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transformation" eType="#//Transformation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Statement" abstract="true" interface="true"
      eSuperTypes="#//Expression"/>
  <eClassifiers xsi:type="ecore:EEnum" name="BinaryFunction">
    <eLiterals name="mult"/>
    <eLiterals name="sum" value="1"/>
    <eLiterals name="divide" value="2"/>
    <eLiterals name="concat" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BinaryOperationExpression" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" lowerBound="1" eType="#//Expression"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" lowerBound="1" eType="#//Expression"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operation" eType="#//BinaryFunction"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TableField">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//Type"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Transformation" eSuperTypes="#//Block">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="returnType" lowerBound="1"
        eType="#//Type"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" upperBound="-1"
        eType="#//Parameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="selfType" lowerBound="1"
        eType="#//Type"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="when" eType="#//BooleanOperationExpression"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="returnStatement" lowerBound="1"
        upperBound="-1" eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Block" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EEnum" name="BinaryFunction">
    <eLiterals name="mult"/>
    <eLiterals name="sum" value="1"/>
    <eLiterals name="divide" value="2"/>
    <eLiterals name="concat" value="3"/>
    <eLiterals name="equal" value="4"/>
    <eLiterals name="notequal" value="6"/>
    <eLiterals name="smaller" value="7"/>
    <eLiterals name="greater" value="7"/>
    <eLiterals name="or" value="8"/>
    <eLiterals name="and" value="9"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanOperationExpression" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operation" eType="#//BooleanFunction"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BooleanFunction">
    <eLiterals name="equal"/>
    <eLiterals name="notequal" value="1"/>
    <eLiterals name="smaller" value="2"/>
    <eLiterals name="greater" value="3"/>
    <eLiterals name="smaller" value="4"/>
    <eLiterals name="greater" value="5"/>
    <eLiterals name="or" value="6"/>
    <eLiterals name="and" value="7"/>
  </eClassifiers>
</ecore:EPackage>
