<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="tqlModel" nsURI="http://www.example.org/tqlModel" nsPrefix="tqlModel">
  <eClassifiers xsi:type="ecore:EEnum" name="Type">
    <eLiterals name="string"/>
    <eLiterals name="integer" value="1"/>
    <eLiterals name="floats" value="2"/>
    <eLiterals name="sets" value="3"/>
    <eLiterals name="DateTime" value="4"/>
    <eLiterals name="Null" value="5"/>
    <eLiterals name="bool" value="6"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Mapping" eSuperTypes="#//Block">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fields" upperBound="-1"
        eType="#//MappingField" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourcetable" lowerBound="1"
        eType="#//SourceTable"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targettable" lowerBound="1"
        eType="#//TargetTable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Table" abstract="true" interface="true"
      eSuperTypes="#//Block">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="columns" lowerBound="1"
        upperBound="-1" eType="#//TableField" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MappingField">
    <eStructuralFeatures xsi:type="ecore:EReference" name="souceField" lowerBound="1"
        eType="#//TableField"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetField" lowerBound="1"
        eType="#//TableField"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="calls" upperBound="-1"
        eType="#//TransformationCall" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BinaryFunction">
    <eLiterals name="mult"/>
    <eLiterals name="sum" value="1"/>
    <eLiterals name="divide" value="2"/>
    <eLiterals name="concat" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TableField">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//Type"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Block" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EEnum" name="BooleanFunction">
    <eLiterals name="equal"/>
    <eLiterals name="notequal" value="1"/>
    <eLiterals name="smaller" value="2"/>
    <eLiterals name="greater" value="3"/>
    <eLiterals name="or" value="6"/>
    <eLiterals name="and" value="7"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TransformationCall">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//TableField"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SourceTable" eSuperTypes="#//Table"/>
  <eClassifiers xsi:type="ecore:EClass" name="TargetTable" eSuperTypes="#//Table"/>
</ecore:EPackage>
